import 'package:flutter/material.dart';
import 'package:friendly_code/core/theme/colors.dart';
import 'package:friendly_code/core/data/venue_repository.dart';
import 'package:friendly_code/core/models/venue_model.dart';
import 'package:friendly_code/core/models/venue_request_model.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

class VenueSearchScreen extends StatefulWidget {
  const VenueSearchScreen({super.key});

  @override
  State<VenueSearchScreen> createState() => _VenueSearchScreenState();
}

class _VenueSearchScreenState extends State<VenueSearchScreen> {
  final TextEditingController _searchController = TextEditingController();
  final VenueRepository _venueRepo = VenueRepository();
  
  List<VenueModel> _searchResults = [];
  bool _isLoading = false;
  String? _error;

  Future<void> _performSearch() async {
    final query = _searchController.text.trim();
    if (query.isEmpty) return;

    setState(() {
      _isLoading = true;
      _error = null;
    });

    try {
      final results = await _venueRepo.searchVenues(query);
      setState(() {
        _searchResults = results;
      });
    } catch (e) {
      setState(() {
        _error = "Error searching venues: $e";
      });
    } finally {
      setState(() {
        _isLoading = false;
      });
    }
  }

  Future<void> _requestToJoin(VenueModel venue) async {
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("You must be logged in to join a venue.")));
      return;
    }

    try {
      final request = VenueRequestModel(
        id: '', // Generated by Firestore or ignored if using .add() with custom serializer handling
        userId: user.uid,
        userEmail: user.email ?? 'Unknown',
        userName: user.displayName ?? 'Unknown',
        type: 'join',
        status: 'pending',
        targetVenueId: venue.id,
        targetVenueName: venue.name,
        createdAt: DateTime.now(),
      );

      await _venueRepo.createVenueRequest(request);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text("Request sent to join ${venue.name}!")));
        Navigator.pop(context); // Go back after request
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text("Error sending request: $e")));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        title: const Text("Join a Venue", style: TextStyle(fontWeight: FontWeight.bold, color: AppColors.title)),
        backgroundColor: Colors.white,
        elevation: 0,
        iconTheme: const IconThemeData(color: AppColors.title),
      ),
      body: Padding(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Search Bar
            Container(
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(16),
                boxShadow: AppColors.softShadow,
              ),
              child: TextField(
                controller: _searchController,
                decoration: InputDecoration(
                  hintText: "Search venue by name...",
                  prefixIcon: const Icon(Icons.search, color: AppColors.premiumBurntOrange),
                  suffixIcon: IconButton(
                    icon: const Icon(Icons.arrow_forward, color: AppColors.premiumBurntOrange),
                    onPressed: _performSearch,
                  ),
                  border: InputBorder.none,
                  contentPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
                ),
                onSubmitted: (_) => _performSearch(),
              ),
            ),
            
            const SizedBox(height: 32),

            // Results Label
            if (_searchResults.isNotEmpty)
              const Text("SEARCH RESULTS", style: TextStyle(color: AppColors.body, fontWeight: FontWeight.bold, fontSize: 12, letterSpacing: 1.5)),
            
            if (_error != null)
              Padding(
                padding: const EdgeInsets.only(top: 16),
                child: Text(_error!, style: const TextStyle(color: Colors.red)),
              ),

            const SizedBox(height: 16),

            // Results List
            Expanded(
              child: _isLoading 
                ? const Center(child: CircularProgressIndicator())
                : _searchResults.isEmpty && _searchController.text.isNotEmpty && !_isLoading
                  ? Center(
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Icon(FontAwesomeIcons.storeSlash, size: 48, color: AppColors.body.withOpacity(0.3)),
                          const SizedBox(height: 16),
                          Text(
                            "No venues found matching '${_searchController.text}'",
                            style: TextStyle(color: AppColors.body.withOpacity(0.5)),
                          ),
                        ],
                      ),
                    )
                  : ListView.builder(
                      itemCount: _searchResults.length,
                      itemBuilder: (context, index) {
                        final venue = _searchResults[index];
                        return Container(
                          margin: const EdgeInsets.only(bottom: 16),
                          padding: const EdgeInsets.all(16),
                          decoration: BoxDecoration(
                            color: Colors.white,
                            borderRadius: BorderRadius.circular(16),
                            boxShadow: AppColors.softShadow,
                          ),
                          child: Row(
                            children: [
                              Container(
                                width: 50,
                                height: 50,
                                decoration: BoxDecoration(
                                  color: AppColors.background,
                                  borderRadius: BorderRadius.circular(12),
                                  image: venue.logoUrl != null
                                    ? DecorationImage(image: NetworkImage(venue.logoUrl!), fit: BoxFit.cover)
                                    : null,
                                ),
                                child: venue.logoUrl == null
                                  ? const Icon(Icons.storefront, color: AppColors.accentOrange)
                                  : null,
                              ),
                              const SizedBox(width: 16),
                              Expanded(
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Text(venue.name, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: AppColors.title)),
                                    Text(venue.address, style: const TextStyle(fontSize: 12, color: AppColors.body)),
                                  ],
                                ),
                              ),
                              ElevatedButton(
                                onPressed: () => _requestToJoin(venue),
                                style: ElevatedButton.styleFrom(
                                  backgroundColor: AppColors.premiumBurntOrange,
                                  foregroundColor: Colors.white,
                                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                                ),
                                child: const Text("Join"),
                              ),
                            ],
                          ),
                        );
                      },
                    ),
            ),
          ],
        ),
      ),
    );
  }
}
