// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYqvC0Ti6ChVnz5eMQhxms4hkgMUxF9PY',
    appId: '1:331010142763:web:cfd9fa17ed9bf99a99f06e',
    messagingSenderId: '331010142763',
    projectId: 'bot-lab-21910',
    authDomain: 'bot-lab-21910.firebaseapp.com',
    databaseURL: 'https://bot-lab-21910.firebaseio.com',
    storageBucket: 'bot-lab-21910.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEinz874_yZycEwKubkgxQWSwmAxrc_MQ',
    appId: '1:331010142763:android:7a5188d055487fe499f06e',
    messagingSenderId: '331010142763',
    projectId: 'bot-lab-21910',
    databaseURL: 'https://bot-lab-21910.firebaseio.com',
    storageBucket: 'bot-lab-21910.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4lhCa7wNMRhg5K3SKaMw17MUE0zxeIUI',
    appId: '1:331010142763:ios:88ba4f825184863f99f06e',
    messagingSenderId: '331010142763',
    projectId: 'bot-lab-21910',
    databaseURL: 'https://bot-lab-21910.firebaseio.com',
    storageBucket: 'bot-lab-21910.firebasestorage.app',
    iosClientId: '331010142763-rviabm6o7i364elvqunpmfgi2infc1mu.apps.googleusercontent.com',
    iosBundleId: 'com.friendlycode.friendlyCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4lhCa7wNMRhg5K3SKaMw17MUE0zxeIUI',
    appId: '1:331010142763:ios:88ba4f825184863f99f06e',
    messagingSenderId: '331010142763',
    projectId: 'bot-lab-21910',
    databaseURL: 'https://bot-lab-21910.firebaseio.com',
    storageBucket: 'bot-lab-21910.firebasestorage.app',
    iosClientId: '331010142763-rviabm6o7i364elvqunpmfgi2infc1mu.apps.googleusercontent.com',
    iosBundleId: 'com.friendlycode.friendlyCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYqvC0Ti6ChVnz5eMQhxms4hkgMUxF9PY',
    appId: '1:331010142763:web:18d8549078a1f50a99f06e',
    messagingSenderId: '331010142763',
    projectId: 'bot-lab-21910',
    authDomain: 'bot-lab-21910.firebaseapp.com',
    databaseURL: 'https://bot-lab-21910.firebaseio.com',
    storageBucket: 'bot-lab-21910.firebasestorage.app',
  );

}
